# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.link_measurement_period import LinkMeasurementPeriod  # noqa: E501
from swagger_client.rest import ApiException


class TestLinkMeasurementPeriod(unittest.TestCase):
    """LinkMeasurementPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkMeasurementPeriod(self):
        """Test LinkMeasurementPeriod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.link_measurement_period.LinkMeasurementPeriod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
