# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.topology_api import TopologyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTopologyApi(unittest.TestCase):
    """TopologyApi unit test stubs"""

    def setUp(self):
        self.api = TopologyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_topology(self):
        """Test case for add_topology

        Send a new topology to SDX-LC  # noqa: E501
        """
        pass

    def test_delete_topology(self):
        """Test case for delete_topology

        Deletes a topology  # noqa: E501
        """
        pass

    def test_delete_topology_version(self):
        """Test case for delete_topology_version

        Deletes a topology version  # noqa: E501
        """
        pass

    def test_get_topology(self):
        """Test case for get_topology

        get an existing topology  # noqa: E501
        """
        pass

    def test_get_topologyby_version(self):
        """Test case for get_topologyby_version

        Find topology by version  # noqa: E501
        """
        pass

    def test_topology_version(self):
        """Test case for topology_version

        Finds topology version  # noqa: E501
        """
        pass

    def test_update_node(self):
        """Test case for update_node

        Update an existing node  # noqa: E501
        """
        pass

    def test_update_topology(self):
        """Test case for update_topology

        Update an existing topology  # noqa: E501
        """
        pass

    def test_upload_file(self):
        """Test case for upload_file

        uploads an topology image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
