# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ConnectionV2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "id": "str",
        "name": "str",
        "endpoints": "list[ConnectionV2Endpoints]",
        "description": "str",
        "notifications": "list[dict(str, object)]",
        "scheduling": "ConnectionScheduling",
        "qos_metrics": "dict(str, ConnectionQosMetrics)",
        "paths": "list[str]",
        "status": "str",
        "complete": "bool",
        "quantity": "int",
        "multi_path": "bool",
        "preempt": "bool",
        "backup_path_type": "str",
        "exclusive_links": "list[Link]",
        "inclusive_links": "list[Link]",
    }

    attribute_map = {
        "id": "id",
        "name": "name",
        "endpoints": "endpoints",
        "description": "description",
        "notifications": "notifications",
        "scheduling": "scheduling",
        "qos_metrics": "qos_metrics",
        "paths": "paths",
        "status": "status",
        "complete": "complete",
        "quantity": "quantity",
        "multi_path": "multi_path",
        "preempt": "preempt",
        "backup_path_type": "backup_path_type",
        "exclusive_links": "exclusive_links",
        "inclusive_links": "inclusive_links",
    }

    def __init__(
        self,
        id=None,
        name=None,
        endpoints=None,
        description=None,
        notifications=None,
        scheduling=None,
        qos_metrics=None,
        paths=None,
        status=None,
        complete=False,
        quantity=None,
        multi_path=None,
        preempt=None,
        backup_path_type=None,
        exclusive_links=None,
        inclusive_links=None,
    ):  # noqa: E501
        """ConnectionV2 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._endpoints = None
        self._description = None
        self._notifications = None
        self._scheduling = None
        self._qos_metrics = None
        self._paths = None
        self._status = None
        self._complete = None
        self._quantity = None
        self._multi_path = None
        self._preempt = None
        self._backup_path_type = None
        self._exclusive_links = None
        self._inclusive_links = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.endpoints = endpoints
        self.description = description
        self.notifications = notifications
        self.scheduling = scheduling
        self.qos_metrics = qos_metrics
        if paths is not None:
            self.paths = paths
        if status is not None:
            self.status = status
        if complete is not None:
            self.complete = complete
        if quantity is not None:
            self.quantity = quantity
        if multi_path is not None:
            self.multi_path = multi_path
        if preempt is not None:
            self.preempt = preempt
        if backup_path_type is not None:
            self.backup_path_type = backup_path_type
        if exclusive_links is not None:
            self.exclusive_links = exclusive_links
        if inclusive_links is not None:
            self.inclusive_links = inclusive_links

    @property
    def id(self):
        """Gets the id of this ConnectionV2.  # noqa: E501


        :return: The id of this ConnectionV2.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConnectionV2.


        :param id: The id of this ConnectionV2.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ConnectionV2.  # noqa: E501


        :return: The name of this ConnectionV2.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConnectionV2.


        :param name: The name of this ConnectionV2.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def endpoints(self):
        """Gets the endpoints of this ConnectionV2.  # noqa: E501


        :return: The endpoints of this ConnectionV2.  # noqa: E501
        :rtype: list[ConnectionV2Endpoints]
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints):
        """Sets the endpoints of this ConnectionV2.


        :param endpoints: The endpoints of this ConnectionV2.  # noqa: E501
        :type: list[ConnectionV2Endpoints]
        """
        if endpoints is None:
            raise ValueError(
                "Invalid value for `endpoints`, must not be `None`"
            )  # noqa: E501

        self._endpoints = endpoints

    @property
    def description(self):
        """Gets the description of this ConnectionV2.  # noqa: E501


        :return: The description of this ConnectionV2.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ConnectionV2.


        :param description: The description of this ConnectionV2.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError(
                "Invalid value for `description`, must not be `None`"
            )  # noqa: E501

        self._description = description

    @property
    def notifications(self):
        """Gets the notifications of this ConnectionV2.  # noqa: E501


        :return: The notifications of this ConnectionV2.  # noqa: E501
        :rtype: list[dict(str, object)]
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications):
        """Sets the notifications of this ConnectionV2.


        :param notifications: The notifications of this ConnectionV2.  # noqa: E501
        :type: list[dict(str, object)]
        """
        if notifications is None:
            raise ValueError(
                "Invalid value for `notifications`, must not be `None`"
            )  # noqa: E501

        self._notifications = notifications

    @property
    def scheduling(self):
        """Gets the scheduling of this ConnectionV2.  # noqa: E501


        :return: The scheduling of this ConnectionV2.  # noqa: E501
        :rtype: ConnectionScheduling
        """
        return self._scheduling

    @scheduling.setter
    def scheduling(self, scheduling):
        """Sets the scheduling of this ConnectionV2.


        :param scheduling: The scheduling of this ConnectionV2.  # noqa: E501
        :type: ConnectionScheduling
        """
        if scheduling is None:
            raise ValueError(
                "Invalid value for `scheduling`, must not be `None`"
            )  # noqa: E501

        self._scheduling = scheduling

    @property
    def qos_metrics(self):
        """Gets the qos_metrics of this ConnectionV2.  # noqa: E501


        :return: The qos_metrics of this ConnectionV2.  # noqa: E501
        :rtype: dict(str, ConnectionQosMetrics)
        """
        return self._qos_metrics

    @qos_metrics.setter
    def qos_metrics(self, qos_metrics):
        """Sets the qos_metrics of this ConnectionV2.


        :param qos_metrics: The qos_metrics of this ConnectionV2.  # noqa: E501
        :type: dict(str, ConnectionQosMetrics)
        """
        if qos_metrics is None:
            raise ValueError(
                "Invalid value for `qos_metrics`, must not be `None`"
            )  # noqa: E501

        self._qos_metrics = qos_metrics

    @property
    def paths(self):
        """Gets the paths of this ConnectionV2.  # noqa: E501


        :return: The paths of this ConnectionV2.  # noqa: E501
        :rtype: list[str]
        """
        return self._paths

    @paths.setter
    def paths(self, paths):
        """Sets the paths of this ConnectionV2.


        :param paths: The paths of this ConnectionV2.  # noqa: E501
        :type: list[str]
        """

        self._paths = paths

    @property
    def status(self):
        """Gets the status of this ConnectionV2.  # noqa: E501

        Connection Status  # noqa: E501

        :return: The status of this ConnectionV2.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ConnectionV2.

        Connection Status  # noqa: E501

        :param status: The status of this ConnectionV2.  # noqa: E501
        :type: str
        """
        allowed_values = ["success", "fail", "scheduled", "provisioining"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}".format(  # noqa: E501
                    status, allowed_values
                )
            )

        self._status = status

    @property
    def complete(self):
        """Gets the complete of this ConnectionV2.  # noqa: E501


        :return: The complete of this ConnectionV2.  # noqa: E501
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this ConnectionV2.


        :param complete: The complete of this ConnectionV2.  # noqa: E501
        :type: bool
        """

        self._complete = complete

    @property
    def quantity(self):
        """Gets the quantity of this ConnectionV2.  # noqa: E501


        :return: The quantity of this ConnectionV2.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ConnectionV2.


        :param quantity: The quantity of this ConnectionV2.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def multi_path(self):
        """Gets the multi_path of this ConnectionV2.  # noqa: E501


        :return: The multi_path of this ConnectionV2.  # noqa: E501
        :rtype: bool
        """
        return self._multi_path

    @multi_path.setter
    def multi_path(self, multi_path):
        """Sets the multi_path of this ConnectionV2.


        :param multi_path: The multi_path of this ConnectionV2.  # noqa: E501
        :type: bool
        """

        self._multi_path = multi_path

    @property
    def preempt(self):
        """Gets the preempt of this ConnectionV2.  # noqa: E501


        :return: The preempt of this ConnectionV2.  # noqa: E501
        :rtype: bool
        """
        return self._preempt

    @preempt.setter
    def preempt(self, preempt):
        """Sets the preempt of this ConnectionV2.


        :param preempt: The preempt of this ConnectionV2.  # noqa: E501
        :type: bool
        """

        self._preempt = preempt

    @property
    def backup_path_type(self):
        """Gets the backup_path_type of this ConnectionV2.  # noqa: E501


        :return: The backup_path_type of this ConnectionV2.  # noqa: E501
        :rtype: str
        """
        return self._backup_path_type

    @backup_path_type.setter
    def backup_path_type(self, backup_path_type):
        """Sets the backup_path_type of this ConnectionV2.


        :param backup_path_type: The backup_path_type of this ConnectionV2.  # noqa: E501
        :type: str
        """
        allowed_values = ["0", "1", "2", "3"]  # noqa: E501
        if backup_path_type not in allowed_values:
            raise ValueError(
                "Invalid value for `backup_path_type` ({0}), must be one of {1}".format(  # noqa: E501
                    backup_path_type, allowed_values
                )
            )

        self._backup_path_type = backup_path_type

    @property
    def exclusive_links(self):
        """Gets the exclusive_links of this ConnectionV2.  # noqa: E501


        :return: The exclusive_links of this ConnectionV2.  # noqa: E501
        :rtype: list[Link]
        """
        return self._exclusive_links

    @exclusive_links.setter
    def exclusive_links(self, exclusive_links):
        """Sets the exclusive_links of this ConnectionV2.


        :param exclusive_links: The exclusive_links of this ConnectionV2.  # noqa: E501
        :type: list[Link]
        """

        self._exclusive_links = exclusive_links

    @property
    def inclusive_links(self):
        """Gets the inclusive_links of this ConnectionV2.  # noqa: E501


        :return: The inclusive_links of this ConnectionV2.  # noqa: E501
        :rtype: list[Link]
        """
        return self._inclusive_links

    @inclusive_links.setter
    def inclusive_links(self, inclusive_links):
        """Sets the inclusive_links of this ConnectionV2.


        :param inclusive_links: The inclusive_links of this ConnectionV2.  # noqa: E501
        :type: list[Link]
        """

        self._inclusive_links = inclusive_links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ConnectionV2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
