# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionV2Endpoints(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'port_id': 'str',
        'vlan': 'str'
    }

    attribute_map = {
        'port_id': 'port_id',
        'vlan': 'vlan'
    }

    def __init__(self, port_id=None, vlan=None):  # noqa: E501
        """ConnectionV2Endpoints - a model defined in Swagger"""  # noqa: E501
        self._port_id = None
        self._vlan = None
        self.discriminator = None
        if port_id is not None:
            self.port_id = port_id
        if vlan is not None:
            self.vlan = vlan

    @property
    def port_id(self):
        """Gets the port_id of this ConnectionV2Endpoints.  # noqa: E501


        :return: The port_id of this ConnectionV2Endpoints.  # noqa: E501
        :rtype: str
        """
        return self._port_id

    @port_id.setter
    def port_id(self, port_id):
        """Sets the port_id of this ConnectionV2Endpoints.


        :param port_id: The port_id of this ConnectionV2Endpoints.  # noqa: E501
        :type: str
        """

        self._port_id = port_id

    @property
    def vlan(self):
        """Gets the vlan of this ConnectionV2Endpoints.  # noqa: E501


        :return: The vlan of this ConnectionV2Endpoints.  # noqa: E501
        :rtype: str
        """
        return self._vlan

    @vlan.setter
    def vlan(self, vlan):
        """Sets the vlan of this ConnectionV2Endpoints.


        :param vlan: The vlan of this ConnectionV2Endpoints.  # noqa: E501
        :type: str
        """

        self._vlan = vlan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionV2Endpoints, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionV2Endpoints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
