# coding: utf-8

"""
    SDX LC

    You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).   # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: yxin@renci.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ConnectionQosMetrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "min_bw": "ConnectionQosUnit",
        "max_delay": "ConnectionQosUnit",
        "max_number_oxps": "ConnectionQosUnit",
        "bandwidth_measured": "float",
        "latency_measured": "float",
        "packetloss_required": "float",
        "packetloss_measured": "float",
        "availability_required": "float",
        "availability_measured": "float",
    }

    attribute_map = {
        "min_bw": "min_bw",
        "max_delay": "max_delay",
        "max_number_oxps": "max_number_oxps",
        "bandwidth_measured": "bandwidth_measured",
        "latency_measured": "latency_measured",
        "packetloss_required": "packetloss_required",
        "packetloss_measured": "packetloss_measured",
        "availability_required": "availability_required",
        "availability_measured": "availability_measured",
    }

    def __init__(
        self,
        min_bw=None,
        max_delay=None,
        max_number_oxps=None,
        bandwidth_measured=None,
        latency_measured=None,
        packetloss_required=None,
        packetloss_measured=None,
        availability_required=None,
        availability_measured=None,
    ):  # noqa: E501
        """ConnectionQosMetrics - a model defined in Swagger"""  # noqa: E501
        self._min_bw = None
        self._max_delay = None
        self._max_number_oxps = None
        self._bandwidth_measured = None
        self._latency_measured = None
        self._packetloss_required = None
        self._packetloss_measured = None
        self._availability_required = None
        self._availability_measured = None
        self.discriminator = None
        if min_bw is not None:
            self.min_bw = min_bw
        if max_delay is not None:
            self.max_delay = max_delay
        if max_number_oxps is not None:
            self.max_number_oxps = max_number_oxps
        if bandwidth_measured is not None:
            self.bandwidth_measured = bandwidth_measured
        if latency_measured is not None:
            self.latency_measured = latency_measured
        if packetloss_required is not None:
            self.packetloss_required = packetloss_required
        if packetloss_measured is not None:
            self.packetloss_measured = packetloss_measured
        if availability_required is not None:
            self.availability_required = availability_required
        if availability_measured is not None:
            self.availability_measured = availability_measured

    @property
    def min_bw(self):
        """Gets the min_bw of this ConnectionQosMetrics.  # noqa: E501


        :return: The min_bw of this ConnectionQosMetrics.  # noqa: E501
        :rtype: ConnectionQosUnit
        """
        return self._min_bw

    @min_bw.setter
    def min_bw(self, min_bw):
        """Sets the min_bw of this ConnectionQosMetrics.


        :param min_bw: The min_bw of this ConnectionQosMetrics.  # noqa: E501
        :type: ConnectionQosUnit
        """

        self._min_bw = min_bw

    @property
    def max_delay(self):
        """Gets the max_delay of this ConnectionQosMetrics.  # noqa: E501


        :return: The max_delay of this ConnectionQosMetrics.  # noqa: E501
        :rtype: ConnectionQosUnit
        """
        return self._max_delay

    @max_delay.setter
    def max_delay(self, max_delay):
        """Sets the max_delay of this ConnectionQosMetrics.


        :param max_delay: The max_delay of this ConnectionQosMetrics.  # noqa: E501
        :type: ConnectionQosUnit
        """

        self._max_delay = max_delay

    @property
    def max_number_oxps(self):
        """Gets the max_number_oxps of this ConnectionQosMetrics.  # noqa: E501


        :return: The max_number_oxps of this ConnectionQosMetrics.  # noqa: E501
        :rtype: ConnectionQosUnit
        """
        return self._max_number_oxps

    @max_number_oxps.setter
    def max_number_oxps(self, max_number_oxps):
        """Sets the max_number_oxps of this ConnectionQosMetrics.


        :param max_number_oxps: The max_number_oxps of this ConnectionQosMetrics.  # noqa: E501
        :type: ConnectionQosUnit
        """

        self._max_number_oxps = max_number_oxps

    @property
    def bandwidth_measured(self):
        """Gets the bandwidth_measured of this ConnectionQosMetrics.  # noqa: E501


        :return: The bandwidth_measured of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._bandwidth_measured

    @bandwidth_measured.setter
    def bandwidth_measured(self, bandwidth_measured):
        """Sets the bandwidth_measured of this ConnectionQosMetrics.


        :param bandwidth_measured: The bandwidth_measured of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._bandwidth_measured = bandwidth_measured

    @property
    def latency_measured(self):
        """Gets the latency_measured of this ConnectionQosMetrics.  # noqa: E501


        :return: The latency_measured of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._latency_measured

    @latency_measured.setter
    def latency_measured(self, latency_measured):
        """Sets the latency_measured of this ConnectionQosMetrics.


        :param latency_measured: The latency_measured of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._latency_measured = latency_measured

    @property
    def packetloss_required(self):
        """Gets the packetloss_required of this ConnectionQosMetrics.  # noqa: E501


        :return: The packetloss_required of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._packetloss_required

    @packetloss_required.setter
    def packetloss_required(self, packetloss_required):
        """Sets the packetloss_required of this ConnectionQosMetrics.


        :param packetloss_required: The packetloss_required of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._packetloss_required = packetloss_required

    @property
    def packetloss_measured(self):
        """Gets the packetloss_measured of this ConnectionQosMetrics.  # noqa: E501


        :return: The packetloss_measured of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._packetloss_measured

    @packetloss_measured.setter
    def packetloss_measured(self, packetloss_measured):
        """Sets the packetloss_measured of this ConnectionQosMetrics.


        :param packetloss_measured: The packetloss_measured of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._packetloss_measured = packetloss_measured

    @property
    def availability_required(self):
        """Gets the availability_required of this ConnectionQosMetrics.  # noqa: E501


        :return: The availability_required of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._availability_required

    @availability_required.setter
    def availability_required(self, availability_required):
        """Sets the availability_required of this ConnectionQosMetrics.


        :param availability_required: The availability_required of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._availability_required = availability_required

    @property
    def availability_measured(self):
        """Gets the availability_measured of this ConnectionQosMetrics.  # noqa: E501


        :return: The availability_measured of this ConnectionQosMetrics.  # noqa: E501
        :rtype: float
        """
        return self._availability_measured

    @availability_measured.setter
    def availability_measured(self, availability_measured):
        """Sets the availability_measured of this ConnectionQosMetrics.


        :param availability_measured: The availability_measured of this ConnectionQosMetrics.  # noqa: E501
        :type: float
        """

        self._availability_measured = availability_measured

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (
                            (item[0], item[1].to_dict())
                            if hasattr(item[1], "to_dict")
                            else item
                        ),
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ConnectionQosMetrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionQosMetrics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
